### ISSUE TITLE
Exception when query includes item not in schema

### ISSUE THREAD

**Issue by thomassuckow** [alekbarszczewski/graphql-query-tree#1]
When the query includes an invalid item (not in schema) this library throws an exception because there are no arguments or type to lookup.

I request that $args default to {} and the $type to undefined. Then it is up to the user to decide if something should be done or just ignore the erroneous item.

**Comment by alekbarszczewski** [comment]
@thomassuckow I am not sure if I understand - if you are trying to query field that's invalid according to GraphQL schema then graphql-js itself throws error like `GraphQLError: Cannot query field "invalid" on type "Post".` for example. Could you provide more info?

**Comment by thomassuckow** [comment]
Interesting, when I try it in our GraphiQL the invalid field is ignored when the query is run. GraphiQL will complain about it in the editor but the query will still execute. We have a custom transport layer over websocket which must inadvertently be bypassing a validator though.

Since this should be getting caught higher up and our setup is why this is happening, I'll close this.
